[package]
name = "a"
version = "0.2.0"
authors = ["msiglreith <m.siglreith@gmail.com"]
edition = "2018"
license = ""
license-file = "../LICENSE.txt"
documentation = ""
homepage = "github.com/msiglreith/ci-test"
repository = "github.com/msiglreith/ci-test"
description = "a"

[lib]
path = "lib.rs"
