[package]
name = "c"
version = "0.3.0"
authors = ["msiglreith <m.siglreith@gmail.com"]
edition = "2018"
license = ""
license-file = ""
documentation = ""
homepage = ""
repository = ""

[lib]
path = "lib.rs"
